# Rita Raher 18-02-2018
# Project Euler
# Problem 2: Even Fibonacci Numbers
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
# https://projecteuler.net/problem=2

j = 0
i = 1
sum = 0

while i <= 4000000:
     j, i  = i, j + i 
     if i % 2 == 0:
        # sum = sum + 1
        sum += i

print("sum of even fibonacci numbers: " , sum)
